### ISSUE TITLE
expand list of types and make configurable

### ISSUE THREAD

**Issue by delanym** [plume-lib/require-javadoc#59]
I only require Javadoc on packages and classes. Since the output doesn't print the type on the same line that is processed I can't filter out methods with grep, so this is essential.

**Comment by mernst** [comment]
Could you please try the `dont-require-fine-grained` branch and let me know whether it works for you?

**Comment by delanym** [comment]
If I choose --dont-require-type=true then I don't get any output.

**Comment by mernst** [comment]
Thanks for the feedback!  Could you please pull and try again?

**Comment by delanym** [comment]
Thats working now. Is it possible to get packages alone?

**Comment by mernst** [comment]
I have pushed a change that warns if a package lacks Javadoc in its `package-info.java` file.
Are you asking for that, or for something different such as a warning if the `package-info.java` file does not exist?

**Comment by delanym** [comment]
I want to see warnings just for the packages—no classes or interfaces.

**Comment by mernst** [comment]
Can you please answer my question from my last comment?  Namely, is the functionality currently in this pull request adequate for your needs, or not?

**Comment by delanym** [comment]
Well of course the package-info.java file must be there, unless a javadoc comment for the package can be found somewhere else?

**Comment by mernst** [comment]
> of course the package-info.java file must be there

No, that is not correct.  There is no requirement that a `package-info.java` file exists.

There are two reasons that a package may lack documentation:
 * because the `package-info.java` file is present but lacks a Javadoc comment.
 * because there is no `package-info.java` file.

My question to you is which of these situations you would like warnings about:  both of them or just one, and if just one, which one?

**Comment by delanym** [comment]
Both!

**Comment by mernst** [comment]
I have added a flag `--require-package-info` that causes an error to be issued for each missing `package-info.java` file.  It seems to work in my tests.  Could you try it out?
